CREATE TABLE TBCLIENTE (
    CODIGO INTEGER NOT NULL,
    NOME VARCHAR(100),
    CIDADE VARCHAR(100),
    UF CHAR(2),
    CONSTRAINT PK_TBCLIENTE PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE GEN_TBCLIENTE_ID;


INSERT INTO TBCLIENTE (CODIGO, NOME, CIDADE, UF) VALUES ((NEXT VALUE FOR GEN_TBCLIENTE_ID), 'Carlos Silva', 'Curitiba', 'PR');

INSERT INTO TBCLIENTE (CODIGO, NOME, CIDADE, UF) VALUES ((NEXT VALUE FOR GEN_TBCLIENTE_ID), 'Mariana Souza', 'São Paulo', 'SP');

INSERT INTO TBCLIENTE (CODIGO, NOME, CIDADE, UF) VALUES ((NEXT VALUE FOR GEN_TBCLIENTE_ID), 'João Pereira', 'Belo Horizonte', 'MG');

INSERT INTO TBCLIENTE (CODIGO, NOME, CIDADE, UF) VALUES ((NEXT VALUE FOR GEN_TBCLIENTE_ID), 'Fernanda Costa', 'Porto Alegre', 'RS');

--------------produto-----------------
CREATE TABLE TBPRODUTO (
    CODIGO INTEGER NOT NULL,
    DESCRICAO VARCHAR(100),
    PRECO_VENDA DECIMAL(12,2),
    CONSTRAINT PK_TBPRODUTO PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE GEN_TBPRODUTO_ID;

INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Notebook Dell Inspiron', 3599.90);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Mouse Sem Fio Logitech', 89.90);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Teclado Mecânico RGB', 249.50);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Monitor 24 Polegadas Full HD', 899.00);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Headset Gamer Surround', 199.99);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Cadeira Gamer Ergonômica', 1299.00);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'HD Externo 1TB USB 3.0', 379.90);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Pen Drive 64GB', 49.90);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Webcam Full HD 1080p', 159.75);
INSERT INTO TBPRODUTO (CODIGO, DESCRICAO, PRECO_VENDA) VALUES ((NEXT VALUE FOR GEN_TBPRODUTO_ID), 'Caixa de Som Bluetooth', 129.90);

------------------------pedido---------------
CREATE TABLE TBPEDIDO (
    NUMERO_PEDIDO INTEGER NOT NULL,
    DATA_EMISSAO DATE,
    CODIGO_CLIENTE INTEGER,
    VALOR_TOTAL DECIMAL(12,2),
    CONSTRAINT PK_TBPEDIDO PRIMARY KEY (NUMERO_PEDIDO),
    CONSTRAINT FK_TBPEDIDO_CLIENTE 
        FOREIGN KEY (CODIGO_CLIENTE) 
        REFERENCES TBCLIENTE (CODIGO)
);

CREATE SEQUENCE GEN_TBPEDIDO_ID;

-------------------itens pedido-----------------------
CREATE TABLE TBPEDIDO_ITEM (
    ID INTEGER NOT NULL,
    NUMERO_PEDIDO INTEGER NOT NULL,
    CODIGO_PRODUTO INTEGER NOT NULL,
    QUANTIDADE DECIMAL(12,3),
    VLR_UNITARIO DECIMAL(12,2),
    VLR_TOTAL DECIMAL(12,2),
    CONSTRAINT PK_TBPEDIDO_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_PEDITEM_PEDIDO 
        FOREIGN KEY (NUMERO_PEDIDO)
        REFERENCES TBPEDIDO (NUMERO_PEDIDO),
    CONSTRAINT FK_PEDITEM_PRODUTO 
        FOREIGN KEY (CODIGO_PRODUTO)
        REFERENCES TBPRODUTO (CODIGO)
);

CREATE SEQUENCE GEN_TBPEDIDO_ITEM_ID;


CREATE TRIGGER TG_TBPEDIDO_ITEM FOR TBPEDIDO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_TBPEDIDO_ITEM_ID;
END^^


